src/components/CardSection/CardSection.css
src/components/CardSection/CardSection.jsx
src/components/Main/Main.jsx
src/components/Novelties/Novelties.css
src/components/Novelties/Novelties.jsx
src/components/PopularProducts/PopularProducts.jsx
src/components/ProductCard/ProductCard.css
src/components/ProductCard/ProductCard.jsx

Создал hoc-компонент CardSection и его дочерние компоненты Novelties и PopularProducts. Изначально хотел работать над ними в разных ветках, но увлекся и сделал все в одной. Если есть предложения и/или замечания, я только за.
Вот так выглядят компоненты:

Feature/CardSection, Novelties, PopularProducts

---

src/components/Main/Main.jsx

Убираю компонент, который был добавлен в качестве филлера

Refactor/Убрать филлерный код

---

package-lock.json
package.json
src/components/Main/Main.jsx
src/components/TopScrollBtn/TopScrollBtn.css
src/components/TopScrollBtn/TopScrollBtn.jsx
src/images/arrow-up.svg

кнопка для прокрутки страницы вверх

---

src/utils/functions/temporaryObjectArrays.js

Эта опечатка никак не влияет на функционал - просто мозолит глаз, что филлерные товары создаются с некорректным именем. Аппрувните, плиз)

Refactor/Исправить опечатку в функции CreateProductsArray

---

src/components/Accordion/Accordion.css
src/components/Accordion/Accordion.jsx
src/images/accordion-chevron.svg

Реализовала компоненту без использования библиотек с эффектами плавного раскрытия и закрытия контента и с эффектом анимации иконки Chevron.

feat: реализовать компоненту Accordion для страницы товара

---

src/components/Login/Login.jsx
src/components/Registration/Registration.jsx
src/hooks/useForm.jsx
src/utils/regEx.js

Валидация через useForm, добавила регулярки и дополнительные сообщения на проверку полей требованиям

feat(useform.jsx): add validation on form registration and login

---

src/components/Accordion/Accordion.css
src/components/App/App.jsx
src/components/Carousel/Carousel.jsx
src/components/Footer/Footer.css
src/components/Footer/Footer.jsx
src/components/MainProductPage/MainProductPage.css
src/components/MainProductPage/MainProductPage.jsx
src/components/SocialLink/SocialLink.css
src/components/SocialLink/SocialLink.jsx

Страница товара с двумя слайдерами

feat(mainproductpage): add component MainProductPage

---

src/components/Carousel/Carousel.css
src/components/MainProductPage/MainProductPage.css
src/components/MainProductPage/MainProductPage.jsx

Исправила описание страницы товара в соответствии с новым макетом

fix(mainproductcard): edit MainProductPage

---

src/components/Catalog/Catalog.jsx
src/components/CatalogCardSection/CatalogCardSection.jsx
src/components/Novelties/Novelties.jsx
src/components/PopularProducts/PopularProducts.jsx
src/components/ProductCard/ProductCard.jsx
src/components/ShoppingCart/ShoppingCart.jsx
src/components/ShoppingCartItem/ShoppingCardItem.jsx
src/utils/functions/calculateTotalPrice.js
src/utils/functions/encodeObjToQuery.js
src/utils/productsApi.js

Написал запросы к бекенду и добавил логику работы с ними в компоненты Catalog, ShoppingCart, ShoppingCartItem и более мелкие. Написал несколько утилитарных функций. Весь код, связанный с api пока что пришлось спрятать под комментариями, так как он без сервера всё равно работать не будет.

Feature/Catalog и ShoppingCart api

---

src/components/MailIcon/MailIcon.jsx
src/components/OrderProduct/OrderProduct.css
src/components/OrderProduct/OrderProduct.jsx
src/components/ThanksForOrder/ThanksForOrder.css
src/components/ThanksForOrder/ThanksForOrder.jsx

Переделал компонент Ваш заказ по фич-листу.
Не стал менять "Бренд" на "Наименование" так как эти данные берутся из корзины.
В будущем, когда корзина будет готова, тогда из нее все и возьмем.
Макета нет, поэтому на глаз...
Исправил подтверждение заказа также по фич-листу (удалил адрес, получателя, заказ)
Исправил в футере "написать письмо"

Переделать Ваш заказ

---

src/components/CardSection/CardSection.jsx
src/components/Catalog/Catalog.jsx

Убрал кнопки "смотреть всё" и отображение общего количества товара в каталоге

fix/убрал лишние элементы

---

src/components/ConfirmPopup/ConfirmPopup.jsx
src/components/PopupWithForm/PopupWithForm.css
src/components/PopupWithForm/PopupWithForm.jsx

Исправила попап подтвеждающий выход из профиля

style(confirmpopup.jsx): restyled component confirmPopup by layout

---

src/components/EmptyCart/EmptyCart.css
src/components/EmptyCart/EmptyCart.jsx
src/components/ShoppingCart/ShoppingCart.css

refactor(emptycart): сверстал EmptyCart по новому дизайну

---

src/components/App/App.jsx
src/components/Main/Main.jsx
src/components/Novelties/Novelties.jsx
src/components/ProductCard/ProductCard.jsx
src/contexts/ProductsContext.js
src/utils/constants.js
src/utils/makeRequest.js
src/utils/productsApi.js

Интеграция с бэкендом по отображению новинок на сайте. 
Изменила getPoroduct, сделала контекст для продукта, сделала подстановку serverHost, чтобы картинки отображались, когда фронтенд запущен локально.

feat: получить новинки с сервера

---

src/components/App/App.jsx
src/components/Header/Header.jsx
src/components/Navigation/Navigation.jsx

Добавила в контекст пользователя функции открытия попапа Логин и Регистрация, рефакторинг пропс в header

fix: добавить в контекст пользователя открытие попапов

---

src/utils/functions/sortProducts.js

Удалил сортировку по алфавиту в CatalogCardSection

refactor(sortproducts): удалил сортировку по алфавиту

---

src/components/ShoppingCartItem/ShoppingCartItem.css
src/utils/functions/defineImage.js
src/utils/productsApi.js

Пофиксил баг, при котором при запросе на корзину, сервер возвращал максимум 12 уникальных карточек

fix(shoppingcart): 12card-bugfix

---

public/index.html
src/components/App/App.jsx
src/components/MainProductPage/MainProductPage.jsx

Тестирование решение проблемы, что страница не отображается при перезагрузке в динамическом роуте

fix(routing): fix routing

---

public/index.html
src/components/App/App.jsx

убрала неиспользуемое свойство isLoggedIn

---

src/components/AboutProject/AboutProject.css
src/components/Header/Header.css
src/components/Logo/Logo.css
src/components/NavigationLink/NavigationLink.css
src/components/NavigationLink/NavigationLink.jsx
src/components/ProductCard/ProductCard.css
src/components/Promo/Promo.css

1. Изменил цвет с #000000 на #21211B и #403F32 у текста в Promo.
2. Изменил цвет с #000000 на #21211B у текста в AboutProject.
3. Поменял разрешение изображения 266х268 на 268x268 в ProductCard.
4. Указал кавычки для названия шрифта "Mulish", поменял цвет с #000000 на #403F32 для ссылок "войти"/"username" и "корзина" в header.
5. Исправил атрибут alt в NavigationLink на более подходящий в для скринридеров.
6. Добавил нижнюю линию в Header, исправил размер Logo.

fix(promo): bug-fixes

---

src/components/ShoppingCart/ShoppingCart.jsx
src/components/ShoppingCartItem/ShoppingCartItem.jsx
src/utils/constants.js

Исправил baseUrl, убрал лишний пропс в ShoppingCart и console.log в ShoppingCartItem

fix: исправить baseUrl на корректный

---

src/utils/regEx.js

Исправила регулярную строку по вводу пароля

fix(regexpassword): fix regexpassword

---

src/components/App/App.jsx
src/components/BreadCrumbs/BreadCrumbs.jsx
src/components/Login/Login.jsx
src/components/NotFoundPage/NotFoundPage.css
src/components/NotFoundPage/NotFoundPage.jsx
src/components/Registration/Registration.jsx

feat(notfoundpage): add notfoundpage

---

src/components/Profile/Profile.jsx
src/components/ProfileAccordion/ProfileAccordion.css

* Добавлена функциональность кнопке "отменить"
* Исправлена высота accordion в профилк

fix(profile): fix button "отменить" accordion in profile

---

src/components/App/App.jsx
src/components/FilterByPrice/FilterByPrice.jsx
src/components/PopupWithFilters/PopupWithFilters.jsx

feat: доделал фильтрацию до конца
